version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/flutter_appauth/android"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "com.android.tools.build:gradle"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"