task:
  name: Run all unit tests
  container:
    image: cirrusci/flutter:stable
  install_melos_script:
    - dart pub global activate melos
  test_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run test:unit --no-select

task:
  name: Build Android example app and run integration tests
  env:
    EMULATOR_API_LEVEL: 28
    ANDROID_ABI: "default;x86"
  container:
    image: cirrusci/flutter:stable
    cpu: 4
    memory: 10G
    kvm: true
  pub_cache:
    folder: ~/.pub-cache
  install_homebrew_script:
  maestro_cache:
    folder: $HOME/maestro-1.4.0/bin
    install_maestro_script:
      - wget https://github.com/mobile-dev-inc/maestro/releases/download/cli-1.4.0/maestro-1.4.0.zip
      - unzip maestro-1.4.0.zip -d $HOME
  install_melos_script:
    - dart pub global activate melos
  build_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run build:example_android
  install_images_script: sdkmanager "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  create_device_script:
    echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator -no-window -verbose -avd test -no-audio -no-window
  wait_for_emulator_script:
    android-wait-for-emulator
  install_app_script:
    - pwd
    - adb install flutter_appauth/example/build/app/outputs/flutter-apk/app-release.apk
  test_script:
    - export PATH="$PATH":"$HOME/maestro-1.4.0/bin"
    - maestro test .mobiledev/signin_endsession.yaml

task:
  name: Build iOS example app
  osx_instance:
    image: monterey-xcode
  pub_cache:
    folder: ~/.pub-cache
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  install_melos_script:
    - dart pub global activate melos
  build_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run build:example_ios

task:
  name: Build macOS example app
  osx_instance:
    image: monterey-xcode
  pub_cache:
    folder: ~/.pub-cache
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  setup_script:
    - flutter config --enable-macos-desktop
  install_melos_script:
    - dart pub global activate melos
  build_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run build:example_macos
