task:
  name: Build Android example
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd example
    - flutter build appbundle

task:
  name: Build iOS example
  osx_instance:
    image: catalina-flutter
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd example
    - flutter build ios --no-codesign
