task:
  name: Run all unit tests
  container:
    image: cirrusci/flutter:stable
  install_melos_script:
    - dart pub global activate melos
  test_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run test:unit --no-select

task:
  name: Build Android example app
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  install_melos_script:
    - dart pub global activate melos
  build_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run build:example_android

task:
  name: Build iOS example app
  osx_instance:
    image: monterey-xcode
  pub_cache:
    folder: ~/.pub-cache
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  install_melos_script:
    - dart pub global activate melos
  build_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run build:example_ios
