task:
  name: Run platform interface tests
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd flutter_appauth_platform_interface
    - flutter test
task:
  name: Build Android example
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd flutter_appauth/example
    - flutter build appbundle

task:
  name: Build iOS example
  osx_instance:
    image: catalina-flutter
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - flutter channel stable
    - flutter upgrade
    - cd flutter_appauth/example
    - flutter build ios --no-codesign
