name: flutter_appauth
repository: https://github.com/MaikuB/flutter_appauth

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - flutter_appauth/*
  - flutter_appauth_platform_interface/*
  - "**/example/*"

ide:
  intellij: false

scripts:
  analyze:
    run: melos exec -c 1 -- "dart analyze . --fatal-infos"
    description: Run dart analyzer in a specific package.
  test:unit:
    description: Run unit tests in a specific package.
    run: melos exec --concurrency=1 -- "flutter test"
    packageFilters:
      dirExists:
        - test
  build:example_android:
    run: |
      melos exec -c 1 -- \
        "flutter build apk"
    description: Build a specific example app for Android.
    packageFilters:
      dirExists:
        - android
      scope: "*example*"
  build:example_ios:
    run: |
      melos exec -c 1 -- \
        "flutter build ios --no-codesign"
    description: Build a specific example app for iOS.
    packageFilters:
      dirExists:
        - ios
      scope: "*example*"
  build:example_macos:
    run: |
      melos exec -c 1 -- \
        "flutter build macos"
    description: Build a specific example app for macOS.
    packageFilters:
      dirExists:
        - macos
      scope: "*example*"
  clean:
    run: git clean -x -d -f -q
    description: Runs git clean as though repo was just checked out

  format: dart format -o write .
