import 'external_user_agent.dart';
import 'request_state.dart';

mixin AuthorizationParameters {
  /// Hint to the Authorization Server about the login identifier the End-User
  /// might use to log in.
  String? loginHint;

  /// List of ASCII string values that specifies whether the Authorization
  /// Server prompts the End-User for reauthentication and consent.
  List<String>? promptValues;

  /// Specifies the external user-agent to use.
  ExternalUserAgent? externalUserAgent;

  /// Specifies the response mode to use.
  String? responseMode;

  /// Controls the `state` parameter for this authorization request.
  ///
  /// Defaults to [AutoGeneratedState], which lets the native AppAuth SDK
  /// generate a cryptographically random value.
  ///
  /// See also:
  /// * [SuppressedState] to omit the state parameter entirely (removes CSRF
  ///   protection — use with care)
  /// * [CustomState] to provide an explicit value
  RequestState state = const AutoGeneratedState();
}
