/// Contains the response from making an authorization request.
class AuthorizationResponse {
  const AuthorizationResponse({
    this.authorizationCode,
    this.codeVerifier,
    this.nonce,
    this.idToken,
    this.accessToken,
    this.authorizationAdditionalParameters,
  });

  /// The authorization code.
  final String? authorizationCode;

  /// The code verifier generated by AppAuth when issuing the authorization
  /// request.
  ///
  /// Use this when exchanging the [authorizationCode] for a token.
  final String? codeVerifier;

  /// The nonce generated by AppAuth when issuing the authorization request.
  ///
  /// Use this when exchanging the [authorizationCode] for a token.
  final String? nonce;

  /// The ID token returned by implicit / hybrid authorization flows.
  final String? idToken;

  /// The access token returned by implicit / hybrid authorization flows.
  final String? accessToken;

  /// Additional parameters included in the response.
  final Map<String, dynamic>? authorizationAdditionalParameters;
}
