/// Controls the `state` parameter sent in OAuth OpenID requests.
///
/// Use [AutoGeneratedState] (the default) to let the native AppAuth SDK
/// generate a cryptographically random value, [SuppressedState] to omit it
/// entirely, or [CustomState] to provide an explicit value.
sealed class RequestState {
  const RequestState();

  /// The underlying state value to send.
  String? get value;
}

/// The native AppAuth SDKs generate a cryptographically random state value.
///
/// This is the default behaviour and is recommended for most use-cases.
///
/// The [value] is always null, since its a placeholder that shall never be
/// provided to the native SDKs.
class AutoGeneratedState extends RequestState {
  const AutoGeneratedState();

  @override
  final String? value = null;
}

/// No state parameter is sent to the IdP.
///
/// Use this when the Identity Provider rejects requests that include a state
/// value or does not echo it back, causing response validation to fail.
class SuppressedState extends RequestState {
  const SuppressedState();

  @override
  final String? value = null;
}

/// An explicit state value provided by the caller.
class CustomState extends RequestState {
  const CustomState(this._value) : assert(_value != '', 'state must not be empty');

  final String _value;

  @override
  String? get value => _value;
}
