name: validate

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
      - hotfix/*
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Run Dart Analyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Install Tools
        run: ./.github/workflows/scripts/install-tools.sh
      - name: Analyze
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true
  build_example_android_stable:
    name: Build Android example app (stable channel)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Install Tools
        run: ./.github/workflows/scripts/install-tools.sh
      - name: Build
        run: melos run build:example_android
  build_example_android_3_19:
      name: Build Android example app (3.19)
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '17'
        - uses: subosito/flutter-action@v2
          with:
            channel: stable
            flutter-version: 3.19.0
            cache: true
            cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
        - name: Install Tools
          run: ./.github/workflows/scripts/install-tools.sh
        - name: Build
          run: melos run build:example_android
  build_example_ios_stable:
    name: Build iOS example app (stable channel)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Install Tools
        run: ./.github/workflows/scripts/install-tools.sh
      - name: Build
        run: melos run build:example_ios
  build_example_ios_3_19:
    name: Build iOS example app (3.19)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Install Tools
        run: ./.github/workflows/scripts/install-tools.sh
      - name: Build
        run: melos run build:example_ios
  build_example_macos_stable:
    name: Build macOS example app (stable channel)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Install Tools
        run: ./.github/workflows/scripts/install-tools.sh
      - name: Build
        run: melos run build:example_macos
  build_example_macos_3_19:
    name: Build macOS example app (3.19)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Install Tools
        run: ./.github/workflows/scripts/install-tools.sh
      - name: Build
        run: melos run build:example_macos
  unit_tests_dart:
    name: Run all unit tests (Dart)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Install Tools
        run: ./.github/workflows/scripts/install-tools.sh
      - name: Run Tests
        run: melos run test:unit --no-select



